InstabotMV/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from InstabotMV.views import MediaList


app_name = 'instabot'

urlpatterns = [
    url('show/(?P<username_url>\w+)/$', views.ShowView.as_view(), name='show'),
    url('login/$', views.LoginView.as_view(), name='login'),
    url('logout/$', views.logout, name='logout'),
    url('dashboard/$', views.DashboardView, name='dashboard'),
    url('newaccount/$', views.NewAccount, name='addaccount'),
    url('statics/$', views.loginReport, name='login2'),
    url('dashboard/$', views.tag_child, name='dashload'),
    url('settings/$', views.Settings, name='settings'),
    url('reports/$',views.report, name='report'),
    #url('ajax/ticker/$', views.ticker, name='counter'),
    url('ajax/validate_username/$', views.test, name='test2'),
    url('hashtag_ajax/$', views.hashtags.as_view(), name='hashtags'),
    url('prueba_ajax/$', views.prueba.as_view(), name='prueba'),
    url('dashboard/task/new$', views.NewTask, name='newTask'),
    url('tags/(?P<id_tag>\d+)/$', views.tags, name='tags'),
    url('change/(?P<cred>\d+)/$', views.changeAccount, name='changeAccount'),
    url('dashboard/task/new/follow-like/$', views.NewFollowLike, name='newFollowLike'),
    url('dashboard/task/new/unfollow-task/$', views.UnfollowTask, name='unfollow_task'),
    url('dashboard/accounts/$', views.UserAccounts.as_view(), name='userAccounts'),
    url('dashboard/delaccount/(?P<id_cred>\d+)/$$', views.DeleteAccount, name='delaccount'),
    url('create/$', views.Create, name='create'),
    url('store-new-task/$', views.StoreTask.as_view(), name='storeTask'),
    url('store-new-task-u/$', views.StoreTaskUser.as_view(), name='storeTaskU'),
    url('delete_task/(?P<id_task>\d+)/$', views.DeleteTask,name="del_task"),
    url('edit_acc/(?P<id_acc>\d+)/$', views.EditAccount,name="edit_acc"),
    url('edit_task/(?P<id_task>\d+)/$', views.EditTask,name="edit_task"),
    url('edit_friendtask/(?P<id_task>\d+)/$', views.EditTask2,name="edit_task2"),
    url('edit_unfollowtask/(?P<id_task>\d+)/$', views.EditUnfollow,name="edit_unfollow"),

    # # ******************************** bot url's ************************************************************
    url('start-bot/$', views.StartBot.as_view(),name='start'),
    url('start/(?P<task>\d+)/$', views.start,name='starter'),
    url('stop-bot/(?P<t>\d+)/$', views.detener, name='detener'),
    url('imprimir/$', views.pruebaimpresion, name='impresion'),
    url('generate/$', views.GenerateRandomUserView.as_view(), name='generate')


]

webinstabot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instabotmv/', include('InstabotMV.urls')),
]

InstabotMV/forms.py
from django import forms
from django.contrib.auth.models import User


from InstabotMV.models import Creds, List_Tag, UsList, HashtagList, Media
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())


class CreateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid name'
    })
    last_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid last name'
    })
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'email')


class ProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email field is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })


class InstaCredsForm(forms.ModelForm):
    insta_user = forms.CharField(max_length=30, error_messages={
        'required': 'The username field is required',
        'unique': 'The username entered is already in our records',
        'invalid': 'Enter a valid username'
    })
    insta_pass = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })

    class Meta:
        model = Creds
        fields = ('insta_user', 'insta_pass',)


class TaglistForm(forms.ModelForm):
    insta_tag = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = List_Tag
        fields = ('insta_tag',)


class UserlistForm(forms.ModelForm):
    insta_us_name = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = UsList
        fields = ('insta_us_name',)


class CommandForm(forms.Form):
    command = forms.CharField(max_length=200)


class CombosTagPadre(forms.Form):
    tag_padre = forms.ModelChoiceField(queryset=Media.objects.all())


class ComboTagHijo(forms.Form):
    tag = forms.CharField(label = 'Puntos a sumar', max_length=100, initial='follow, me', required=True)

InstabotMV/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.contrib import messages

from django.contrib.auth import authenticate, login as login_django, logout as logout_django
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import *
from django.urls import reverse
from InstabotMV.models import Creds, List_Tag, Media,HashtagList,Packages
from .forms import LoginForm, CreateUserForm, TaglistForm, UserlistForm, ComboTagHijo
from InstabotMV.forms import InstaCredsForm
from django.db.models import Q

from django.views.generic import View, DetailView, TemplateView, UpdateView, DeleteView, ListView
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http import JsonResponse
import urllib, json
from datetime import date, timedelta
from InstabotMV.src.sql_updates import update_creds
from switchcase import switch
from InstabotMV.src.sql_updates import good_pass
# *************************************************Bot imports**********************************************************

import time

from InstabotMV.src.instabot import InstaBot
from InstabotMV.src.check_status import check_status
from InstabotMV.src.feed_scanner import feed_scanner
from InstabotMV.src.follow_protocol import follow_protocol
from InstabotMV.src.unfollow_protocol import unfollow_protocol
from InstabotMV.src.bsScarp import scrapImg, scrap_us
from InstabotMV.forms import ComboTagHijo
from InstabotMV.src.us_scrap import scrapUsr
from InstabotMV.src.friendListscrap import validat
from InstabotMV.src.sql_updates import update_creds

import smtplib
import datetime
import logging
import random
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic.edit import FormView
from django.shortcuts import redirect


from .forms import GenerateRandomUserForm
from InstabotMV.task import create_random_user_accounts,imprimir,runbot,stop

class GenerateRandomUserView(FormView):
    template_name = 'generate_random_users.html'
    form_class = GenerateRandomUserForm

    def form_valid(self, form):
        total = form.cleaned_data.get('total')
        create_random_user_accounts.delay(total)
        messages.success(self.request, 'We are generating your random users! Wait a moment and refresh this page.')
        return redirect('users_list')

def pruebaimpresion(self):
    imprimir.delay()
    return redirect('instabot:dashboard')
aux=1

def compar_task(task_id, user_n):
    valu=False
    task=Task.objects.all()
    for t in range(0,len(task)):
        if user_n.task==task[t]:
            valu=True
    return valu



# ****************************************************General***********************************************************

def hastagform(request):
    form =ComboTagHijo()
    return render(request, 'includes/audience/hashtags.html',{'form':form})

def hashtag_read(request):
    if request.method =="POST":
            form= ComboTagHijo(request.POST)
            response = ''
            for key, value in request.POST.items():
                response +='key:%s value:%s\n' %(key, value)
                return HttpResponse(response)
    else:
            form= ComboTagHijo(request) #hacemos el formulario en blanco

    return render(request,'includes/audience/hashtags.html',{'form':form})


def tag_child(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        task =Task()#inicializacion de task
        task.user=user#Se le asigna un usuario a la task
        task.save()

        return redirect('instabot:dashload')

    else:
       return redirect('create.html')

def CreateTask(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        task = Task()  # inicializacion de task
        task.user = user  # Se le asigna un usuario a la task
        task.save()

        return redirect('instabot:dashload')

class ShowView(DetailView):
    model = User
    template_name = 'show.html'
    slug_field = 'username'
    slug_url_kwarg = 'username_url'


class LoginView(View):
    form = LoginForm()
    message = " "
    template = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('instabot:dashboard')
        return render(request, self.template, self.get_context())

    def post(self, request, *args, **kwargs):
        username_post = request.POST['username']
        password_post = request.POST['password']
        user = authenticate(username=username_post, password=password_post)
        print(user)
        if user.is_superuser == 1:
            login_django(request, user)
            return redirect('instabot:userAccounts')
        elif user.is_superuser == 0:
            login_django(request, user)
            return redirect('instabot:userAccounts')
        else:
            self.message = "Username o password incorrectos"

        return render(request, self.template, self.get_context())

    def get_context(self):
        return {'form': self.form, 'message': self.message}


@login_required(login_url='instabot:login')
def logout(request):
    logout_django(request)
    return redirect('instabot:login')
@login_required(login_url='/instabotmv/login')
def DashboardView(request):
    user = User.objects.get(id=request.user.id) #Get the current user logged in
    ll=LastLogin.objects.get(user=user)
    cred=ll.cred
    ticklimit=0
    AT=Task.objects.all() #Get All the Task in system
    LT=[] ##Empty list for List of Task
    UX=[]
    z="Hola esto es una prueba"
    count=0
    UN=Username.objects.all() #Limit the ticker number.
    for t in range(0,len(UN)):
        if UN[t].cred_us==ll.cred.insta_user and count<=75 :
            count+=1
            UX.append(UN[t])
    print(ll.cred.insta_user)
    print(len(UX))
    for x in range(0,len(AT)):
       if AT[x].creds==cred:#If the task has the current logged user add it to the LT list
           #print(AT[x].user.username)
           LT.append(AT[x])
           #print("lt se acaba de llenar")
    if len(LT)==0:
        empty=True
        print(LT)
        print("lt esta vacio")
        return render(request, 'dashboard.html', {'ll':ll,'LT':LT,'empty':empty,'UN':UN}) 

    return render(request, 'dashboard.html', {'ll':ll,'LT':LT,'UN':UN,'UX':UX})

def changeAccount(request,cred):
    user = User.objects.get(id=request.user.id)
    ll=LastLogin.objects.get(id=user.id)
    credex= Creds.objects.get(id=cred)
    ll.cred=credex
    ll.save()
    return redirect('instabot:dashboard')




class DashTaskLoad(LoginRequiredMixin, View):  #vista que servira para redireccionar la task guardada en new task excepto paara los unfollows

    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):

        context = {
            'user': request.user
            }

        return render(request, 'dashboard.html', context)


class DashboardClient(LoginRequiredMixin, View):
    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):

        return render(request, 'users/botDashboardClient.html')


class UsersView(LoginRequiredMixin, View):
    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):
        users_in_system = User.objects.filter(is_superuser=0)

        context = {
            'users': users_in_system
        }
        return render(request, 'admin/clients.html', context)


class UserAccounts(LoginRequiredMixin, View):
    login_url = 'instabot:login'
    template_name = 'users/mybot.html'
    
    
    def get(self, request, *args, **kwargs):
        
        user = User.objects.get(id=request.user.id) #Get the current user logged in
        ll=LastLogin.objects.get(user=user)
        cred=ll.cred
        packs= Packages.objects.all()
        user=User.objects.get(id=request.user.id) #Obtencion del usuario logeado
        creds = Creds.objects.all() #Obtencion de todas las credenciales 
        lcreds=[] #Inicializacion de lista de credenciales
        finfo=[]

        for x in range(0,len(creds)):
            #print(creds[x].ceiling)
            if creds[x].user==user:
                lcreds.append(creds[x])
                finfo=scrap_us(creds[x].insta_user)
                if finfo:
                    creds[x].insta_followers=finfo[0]
                    creds[x].insta_followings=finfo[2]
                else:
                    creds[x].insta_followers=False
                    creds[x].insta_followings=False
            

        return render(request, 'users/mybot.html', {'lcreds':lcreds,'ll':ll, 'packs':packs})

    def post(self, request):
        user = User.objects.get(id=request.user.id) #Get the current user logged in
        ll=LastLogin.objects.get(user=user)
        cred=ll.cred
        fo_info=scrap_us(request.POST.get('insta_user'))
        if request.method == 'POST':
            valid=validat( request.POST.get('insta_user'), request.POST.get('insta_pass') )
            if valid==2:
                user=User.objects.get(id=request.user.id) # Se toma el usuario django que eta logeado.
                cred = Creds()  # inicializacion de Credentials
                cred.user = user  # Se le asigna un usuario a la task
                cred.insta_user=request.POST.get('insta_user')
                cred.insta_pass=request.POST.get('insta_pass')
                cred.imgUrl=scrapImg(request.POST.get('insta_user'))
                cred.pack_id=request.POST.get('pack')
                cred.insta_followers=fo_info[0]
                cred.insta_followings=fo_info[1]
                cred.save()          
                messages.success(request, 'You are welcome %s to Ngage Social' % (request.POST.get('insta_user')))
                return redirect('instabot:userAccounts')
            else:

InstabotMV/templates/create.html
{% extends 'base/base.html' %}
{% block body %}
    <h3>Registrarme</h3>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Registrarme" class="btn">
</form>
{% endblock %}

InstabotMV/templates/dashboard.html
{% extends 'base/base.html' %}
{% load static %}
{% block navbar %}
<nav class="navbar navbar-inverse">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <a href="{% url 'instabot:dashboard' %}"><h4 class="left navbar-text">Ngage Social</h4></a>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <h4 class="navbar-text" style="padding-left: 63px;">Current Plan: {{ll.cred.pack.pack_name}}</h4>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ ll.cred.insta_user }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'instabot:userAccounts' %}">Accounts</a></li>
                            <li><a href="#">Billing Profile</a></li>
                            <li><a href="{% url 'instabot:settings' %}">Settings</a></li>
                            <li><a href="{% url 'instabot:report'%}">Reports</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'instabot:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h4 class="left">TASKS</h4>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <a href="{% url 'instabot:newTask' %}" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add new
            </a>
        </div>
    </div>

  
    {% if empty%}
    <h3 class="text-center">Welcome, <span style="color:#2C7CB2;">{{ll.cred.insta_user}}</span>! Let's start your promotion. Please create a new <span style="color:#2C7CB2;">Task</span> </h3>

    {%endif%}
    
    
{% for task in LT %}


<hr class="divider">


        
        <div class="row">
                <div class="col-sm-4 col-sm-offset-4  text-center">
                    <div class="gradiente">
    
                        <p class="hashtags">{{task.tags}}</p>
</div>

                                <ul class="list-inline">
                                        
                                    <li><a class="btn dropdown" data-toggle="collapse" data-target="#1{{task.id}}" data-parent="#myGroup"><i class="icon-chevron-right"></i> Results</a></li>
                                    <li>|</li>
            <li><a class="btn dropdown" data-toggle="collapse" data-target="#2{{task.id}}" data-parent="#myGroup"><i class="icon-chevron-right"></i> Targets</a></li>
            <li>|</li>
        <li><a class="btn dropdown" data-toggle="collapse" data-target="#3{{task.id}}" data-parent="#myGroup"><i class="icon-chevron-right"></i> Options</a></li>
            
                                </ul>
                        </div>
                    </div>
                </div>
            </div>
        

</div>



<div class="row">
    <div class="col-sm-4 col-sm-offset-4  text-center">
        <div id="myGroup">
            
            <div class=" accordion-group">
                <div class="collapse indent" id="1{{task.id}}">
                        <div class="tick">
                            
                                {% for u in UX%}
                                <p>{{task.id}}--l---{{u.task}}</p>
                                <p>             v             </p>
                                {% if task.id == u.task %}
                                <a  href="https://www.instagram.com/{{u.username}}/">
                                <img class="ticker" style="border-radius: 50%; width: 40px;height: 40px;" src="{{u.picUrl}}" alt="user-pic">
                                </a>
                        
                        {% if task.unfollow%}
                        <i class="glyphicon min glyphicon-minus-sign"></i>
                        
                        
                        {%else%}
                        <i class="glyphicon glyphicon-user gli"></i>
                        {%endif%}
                        
                        
                        
                                {% endif%}
                                {% endfor%}
                                 </div>
                </div>
            
                <div class="collapse indent text-center" id="2{{task.id}}">
                    <div class="centrar" style="text-align:center;
                    word-wrap: break-word;">
                        {{task.tags}}
                         </div>
                </div>
            
                <div class="collapse" id="3{{task.id}}">
                        <div class="centrar">
                                
                                 </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  
    </div>

    <form>
    <div class="text-center">
        {% if task.active%}
        {% if task.sleep_mod%}
        <div class="simulating">
            <h3>Simulating human behaviour.
                    Ngage is coming in some minutes.Feel free to close this window. Task is running in Cloud.</h3>
       </div>
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        {%else%}
        <div class="simulating">
            <h3>Simulating human behaviour.
                    Feel free to close this window. Task is running in Cloud.</h3>
       </div>
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
      
        {%endif%}
       {% endif%}
       <div class="text-center" display="inline-block-elements">

            <a href="#link" class="btn btn-primary disabled btn-lit-circle" role="button">
                    <i class="glyphicon glyphicon-heart-empty"></i>
                    {% if task.unfollow%}
                    <a href="#link" class="btn btn-primary disabled btn-lit-circle" role="button">
                        <i class="fas fa-user-minus"></i>
                </a>
            {%else %}
            <a href="#link" class="btn btn-primary disabled btn-lit-circle" role="button">
                <i class="fas fa-user-plus"></i>
        </a>
            {%endif%}
            {% if task.active%}
            <a href="{% url 'instabot:detener' task.id%}"  class="btn btn-played btn-primary btn-circle  btn-xl" role="button">
                    <i  style="margin-top: 7px;margin-left: 3px;" class='glyphicon glyphicon-pause'></i>
            </a>

            
            {% else%}
            <a href="{% url 'instabot:starter' task.id%}" class="btn btn-play btn-primary  btn-circle btn-xl" role="button">
                    <i class='glyphicon glyphicon-play'></i>
            </a>
            {%endif%}
            {%if task.friendlist%}
                
            <a href="{% url 'instabot:edit_task2' task.id%}" class="btn btn-primary  btn-lit-circle" role="button">
                    <i class="glyphicon glyphicon-pencil"></i>
            </a>
            {%elif task.unfollow%}
            <a href="{% url 'instabot:edit_unfollow' task.id%}" class="btn btn-primary  btn-lit-circle" role="button">
                <i class="glyphicon glyphicon-pencil"></i>
        </a>
            
            {%else %}
            <a href="{% url 'instabot:edit_task' task.id%}" class="btn btn-primary  btn-lit-circle" role="button">
                <i class="glyphicon glyphicon-pencil"></i>
        </a>
            {%endif%}
            <a href="{% url 'instabot:del_task' task.id%}" class="btn btn-primary btn-lit-circle" role="button">
                    <i class="glyphicon glyphicon-trash"></i>
            </a>
       </div>
       {% if task.active%}
       <div  style="margin-left: 135px;margin-top: -16px;" class="text-center">
            <i style="color:#2C7CB2;" class='glyphicon  rotor glyphicon-refresh' style=""></i>
            <label style="color:#2C7CB2;">running</label>
       </div>
       {%endif%}

{% endfor%}
<br>
   <div>
   {% if object_list %}
    {% for media in object_list %}
        <li>{{ media.code }}</li>

    {% endfor %}
    {% else %}


   {% endif %}

   </div>


{% endblock %}

InstabotMV/templates/dashboardClient.html
{% extends 'base/base.html' %}
{% load static %}

{% block navbar %}
    <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <div class="mdl-layout-spacer"></div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">
        <label class="mdl-button mdl-js-button mdl-button--icon"
               for="fixed-header-drawer-exp">
          <i class="material-icons">search</i>
        </label>
        <div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" type="text" name="sample"
                 id="fixed-header-drawer-exp">
        </div>
      </div>
    </div>
  </header>
{% endblock %}

    {% block sidepanel %}
        <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
{#            <img class="center-img" src="{% static "img/ngage-web.png" %}" alt="" width="170" height="50">#}
{#            <br><br>#}
{#            <hr class="divider">#}
            <div class="demo-list-action mdl-list">
              <div class="mdl-list__item">
                <span class="mdl-list__item-primary-content center-account-circle">
                  <i class="material-icons mdl-list__item-avatar" id="accountInsta">person</i>
                </span>
              </div>
                <h5 class="center">{{ user.username }}</h5>
            </div>

            <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
                <a class="mdl-navigation__link white-text" href="{% url 'instabot:dashboard' %}">
                    <i class="material-icons">home</i>
                    &nbsp;Home Client
                </a>
                <a class="mdl-navigation__link" href="{% url 'instabot:profile' %}">
                    <i class="material-icons">person</i>
                    &nbsp;My Profile
                </a>
                <a class="mdl-navigation__link" href="{% url 'instabot:logout' %}">
                    <i class="material-icons">exit_to_app</i>
                    &nbsp; Logout
                </a>
            </nav>
        </div>
    {% endblock %}
{% block body %}
{% endblock %}

InstabotMV/templates/show.html
{% extends 'dashboard.html' %}

{% block body %}
<h3>Hola, {{ user.username }}</h3>
{% endblock %}

InstabotMV/templates/xxxx.html
<div class="text-center" display="inline-block-elements">
        <div>
            
                    {% if task.active%}
                            <span>
                                    <button type="button" class="btn btn-primary btn-lit-circle btn-xl" >
                                        <i class="glyphicon glyphicon-heart-empty"></i>
                                    </button>
                                   
                        <span>
                                <button  class="btn btn-primary btn-lit-circle btn-xl " >
                                    <i class="glyphicon glyphicon-user"></i>
            
                                </button>
                        </span>
                        <form action="{% url 'instabot:detener' task.id%}" method="post" >
                            {% csrf_token %}

                    <button type="submit" class="btn btn-played btn-primary btn-circle btn-xl" id="load"
                         data-loading-text="<i class='fa fa-refresh fa-spin'></i>">
                        <i class='glyphicon glyphicon-play'></i>
                    </button>
                
                    <style>
                        .btn-played {
                          border: 16px solid #f3f3f3;
                          border-radius: 50%;
                          border-top: 16px solid #3498db;
                          width: 120px;
                          height: 120px;
                          -webkit-animation: spin 2s linear infinite; /* Safari */
                          animation: spin 2s linear infinite;
                        }
                        
                        /* Safari */
                        @-webkit-keyframes spin {
                          0% { -webkit-transform: rotate(0deg); }
                          100% { -webkit-transform: rotate(360deg); }
                        }
                        
                        @keyframes spin {
                          0% { transform: rotate(0deg); }
                          100% { transform: rotate(360deg); }
                        }
                        </style>
                        </form>
                    {%else%}
                    
                    

                <span>
                        <button type="button" class="btn btn-primary btn-lit-circle btn-xl" >
                            <i class="glyphicon glyphicon-heart-empty"></i>
                        </button>
                       
            <span>
                    <button  class="btn btn-primary btn-lit-circle btn-xl " >
                        <i class="glyphicon glyphicon-user"></i>

                    </button>
            </span>
                            {% csrf_token %}
                            <form action="{% url 'instabot:starter' task.id%}" method="post" >
                    <button type="submit" class="btn btn-play btn-primary btn-circle btn-xl" id="load"
                         data-loading-text="<i class='fa fa-refresh fa-spin'></i>">
                        <i class='glyphicon glyphicon-play'></i>
                    </button>
                </form>
            
                    {%endif%}
    
                
                    
            <span>         
                <button  class="btn btn-primary btn-lit-circle btn-xl">
                        <a href ="{% url 'instabot:del_task' task.id%}"></a>
                    <i class="glyphicon glyphicon-pencil"></i>
                </button>
            </span>
            <span>         
                    <button  class="btn btn-primary btn-lit-circle btn-xl">
                            <a href ="{% url 'instabot:del_task' task.id%}"></a>
                        <i class="glyphicon glyphicon-trash"></i>
                    </button>
                </span>

           <span>
               <p>{{status}}</p>
           </span>

        </div>
    </div>