InstabotMV/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from InstabotMV.views import MediaList


app_name = 'instabot'

urlpatterns = [
    url('show/(?P<username_url>\w+)/$', views.ShowView.as_view(), name='show'),
    url('login/$', views.LoginView.as_view(), name='login'),
    url('logout/$', views.logout, name='logout'),
    url('dashboard/$', views.DashboardView, name='dashboard'),
    url('newaccount/$', views.NewAccount, name='addaccount'),
    url('statics/$', views.loginReport, name='login2'),
    url('dashboard/$', views.tag_child, name='dashload'),
    url('settings/$', views.Settings, name='settings'),
    url('reports/$',views.report, name='report'),
    #url('ajax/ticker/$', views.ticker, name='counter'),
    url('ajax/validate_username/$', views.test, name='test2'),
    url('hashtag_ajax/$', views.hashtags.as_view(), name='hashtags'),
    url('prueba_ajax/$', views.prueba.as_view(), name='prueba'),
    url('dashboard/task/new$', views.NewTask, name='newTask'),
    url('tags/(?P<id_tag>\d+)/$', views.tags, name='tags'),
    url('change/(?P<cred>\d+)/$', views.changeAccount, name='changeAccount'),
    url('dashboard/task/new/follow-like/$', views.NewFollowLike, name='newFollowLike'),
    url('dashboard/task/new/unfollow-task/$', views.UnfollowTask, name='unfollow_task'),
    url('dashboard/accounts/$', views.UserAccounts.as_view(), name='userAccounts'),
    url('dashboard/delaccount/(?P<id_cred>\d+)/$$', views.DeleteAccount, name='delaccount'),
    url('create/$', views.Create, name='create'),
    url('store-new-task/$', views.StoreTask.as_view(), name='storeTask'),
    url('store-new-task-u/$', views.StoreTaskUser.as_view(), name='storeTaskU'),
    url('delete_task/(?P<id_task>\d+)/$', views.DeleteTask,name="del_task"),
    url('edit_acc/(?P<id_acc>\d+)/$', views.EditAccount,name="edit_acc"),
    url('edit_task/(?P<id_task>\d+)/$', views.EditTask,name="edit_task"),
    url('edit_friendtask/(?P<id_task>\d+)/$', views.EditTask2,name="edit_task2"),
    url('edit_unfollowtask/(?P<id_task>\d+)/$', views.EditUnfollow,name="edit_unfollow"),

    # # ******************************** bot url's ************************************************************
    url('start-bot/$', views.StartBot.as_view(),name='start'),
    url('start/(?P<task>\d+)/$', views.start,name='starter'),
    url('stop-bot/(?P<t>\d+)/$', views.detener, name='detener'),
    url('imprimir/$', views.pruebaimpresion, name='impresion'),
    url('generate/$', views.GenerateRandomUserView.as_view(), name='generate')


]

webinstabot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instabotmv/', include('InstabotMV.urls')),
]

InstabotMV/forms.py
from django import forms
from django.contrib.auth.models import User


from InstabotMV.models import Creds, List_Tag, UsList, HashtagList, Media
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())


class CreateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid name'
    })
    last_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid last name'
    })
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'email')


class ProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email field is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })


class InstaCredsForm(forms.ModelForm):
    insta_user = forms.CharField(max_length=30, error_messages={
        'required': 'The username field is required',
        'unique': 'The username entered is already in our records',
        'invalid': 'Enter a valid username'
    })
    insta_pass = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })

    class Meta:
        model = Creds
        fields = ('insta_user', 'insta_pass',)


class TaglistForm(forms.ModelForm):
    insta_tag = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = List_Tag
        fields = ('insta_tag',)


class UserlistForm(forms.ModelForm):
    insta_us_name = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = UsList
        fields = ('insta_us_name',)


class CommandForm(forms.Form):
    command = forms.CharField(max_length=200)


class CombosTagPadre(forms.Form):
    tag_padre = forms.ModelChoiceField(queryset=Media.objects.all())


class ComboTagHijo(forms.Form):
    tag = forms.CharField(label = 'Puntos a sumar', max_length=100, initial='follow, me', required=True)

InstabotMV/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.contrib import messages

from django.contrib.auth import authenticate, login as login_django, logout as logout_django
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import *
from django.urls import reverse
from InstabotMV.models import Creds, List_Tag, Media,HashtagList,Packages
from .forms import LoginForm, CreateUserForm, TaglistForm, UserlistForm, ComboTagHijo
from InstabotMV.forms import InstaCredsForm
from django.db.models import Q

from django.views.generic import View, DetailView, TemplateView, UpdateView, DeleteView, ListView
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http import JsonResponse
import urllib, json
from datetime import date, timedelta
from InstabotMV.src.sql_updates import update_creds
from switchcase import switch
from InstabotMV.src.sql_updates import good_pass
# *************************************************Bot imports**********************************************************

import time

from InstabotMV.src.instabot import InstaBot
from InstabotMV.src.check_status import check_status
from InstabotMV.src.feed_scanner import feed_scanner
from InstabotMV.src.follow_protocol import follow_protocol
from InstabotMV.src.unfollow_protocol import unfollow_protocol
from InstabotMV.src.bsScarp import scrapImg, scrap_us
from InstabotMV.forms import ComboTagHijo
from InstabotMV.src.us_scrap import scrapUsr
from InstabotMV.src.friendListscrap import validat
from InstabotMV.src.sql_updates import update_creds

import smtplib
import datetime
import logging
import random
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic.edit import FormView
from django.shortcuts import redirect


from .forms import GenerateRandomUserForm
from InstabotMV.task import create_random_user_accounts,imprimir,runbot,stop

class GenerateRandomUserView(FormView):
    template_name = 'generate_random_users.html'
    form_class = GenerateRandomUserForm

    def form_valid(self, form):
        total = form.cleaned_data.get('total')
        create_random_user_accounts.delay(total)
        messages.success(self.request, 'We are generating your random users! Wait a moment and refresh this page.')
        return redirect('users_list')

def pruebaimpresion(self):
    imprimir.delay()
    return redirect('instabot:dashboard')
aux=1

def compar_task(task_id, user_n):
    valu=False
    task=Task.objects.all()
    for t in range(0,len(task)):
        if user_n.task==task[t]:
            valu=True
    return valu



# ****************************************************General***********************************************************

def hastagform(request):
    form =ComboTagHijo()
    return render(request, 'includes/audience/hashtags.html',{'form':form})

def hashtag_read(request):
    if request.method =="POST":
            form= ComboTagHijo(request.POST)
            response = ''
            for key, value in request.POST.items():
                response +='key:%s value:%s\n' %(key, value)
                return HttpResponse(response)
    else:
            form= ComboTagHijo(request) #hacemos el formulario en blanco

    return render(request,'includes/audience/hashtags.html',{'form':form})


def tag_child(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        task =Task()#inicializacion de task
        task.user=user#Se le asigna un usuario a la task
        task.save()

        return redirect('instabot:dashload')

    else:
       return redirect('create.html')

def CreateTask(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        task = Task()  # inicializacion de task
        task.user = user  # Se le asigna un usuario a la task
        task.save()

        return redirect('instabot:dashload')

class ShowView(DetailView):
    model = User
    template_name = 'show.html'
    slug_field = 'username'
    slug_url_kwarg = 'username_url'


class LoginView(View):
    form = LoginForm()
    message = " "
    template = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('instabot:dashboard')
        return render(request, self.template, self.get_context())

    def post(self, request, *args, **kwargs):
        username_post = request.POST['username']
        password_post = request.POST['password']
        user = authenticate(username=username_post, password=password_post)
        print(user)
        if user.is_superuser == 1:
            login_django(request, user)
            return redirect('instabot:userAccounts')
        elif user.is_superuser == 0:
            login_django(request, user)
            return redirect('instabot:userAccounts')
        else:
            self.message = "Username o password incorrectos"

        return render(request, self.template, self.get_context())

    def get_context(self):
        return {'form': self.form, 'message': self.message}


@login_required(login_url='instabot:login')
def logout(request):
    logout_django(request)
    return redirect('instabot:login')
@login_required(login_url='/instabotmv/login')
def DashboardView(request):
    user = User.objects.get(id=request.user.id) #Get the current user logged in
    ll=LastLogin.objects.get(user=user)
    cred=ll.cred
    ticklimit=0
    AT=Task.objects.all() #Get All the Task in system
    LT=[] ##Empty list for List of Task
    UX=[]
    z="Hola esto es una prueba"
    count=0
    UN=Username.objects.all() #Limit the ticker number.
    for t in range(0,len(UN)):
        if UN[t].cred_us==ll.cred.insta_user and count<=75 :
            count+=1
            UX.append(UN[t])
    print(ll.cred.insta_user)
    print(len(UX))
    for x in range(0,len(AT)):
       if AT[x].creds==cred:#If the task has the current logged user add it to the LT list
           #print(AT[x].user.username)
           LT.append(AT[x])
           #print("lt se acaba de llenar")
    if len(LT)==0:
        empty=True
        print(LT)
        print("lt esta vacio")
        return render(request, 'dashboard.html', {'ll':ll,'LT':LT,'empty':empty,'UN':UN}) 

    return render(request, 'dashboard.html', {'ll':ll,'LT':LT,'UN':UN,'UX':UX})

def changeAccount(request,cred):
    user = User.objects.get(id=request.user.id)
    ll=LastLogin.objects.get(id=user.id)
    credex= Creds.objects.get(id=cred)
    ll.cred=credex
    ll.save()
    return redirect('instabot:dashboard')




class DashTaskLoad(LoginRequiredMixin, View):  #vista que servira para redireccionar la task guardada en new task excepto paara los unfollows

    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):

        context = {
            'user': request.user
            }

        return render(request, 'dashboard.html', context)


class DashboardClient(LoginRequiredMixin, View):
    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):

        return render(request, 'users/botDashboardClient.html')


class UsersView(LoginRequiredMixin, View):
    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):
        users_in_system = User.objects.filter(is_superuser=0)

        context = {
            'users': users_in_system
        }
        return render(request, 'admin/clients.html', context)


class UserAccounts(LoginRequiredMixin, View):
    login_url = 'instabot:login'
    template_name = 'users/mybot.html'
    
    
    def get(self, request, *args, **kwargs):
        
        user = User.objects.get(id=request.user.id) #Get the current user logged in
        ll=LastLogin.objects.get(user=user)
        cred=ll.cred
        packs= Packages.objects.all()
        user=User.objects.get(id=request.user.id) #Obtencion del usuario logeado
        creds = Creds.objects.all() #Obtencion de todas las credenciales 
        lcreds=[] #Inicializacion de lista de credenciales
        finfo=[]

        for x in range(0,len(creds)):
            #print(creds[x].ceiling)
            if creds[x].user==user:
                lcreds.append(creds[x])
                finfo=scrap_us(creds[x].insta_user)
                if finfo:
                    creds[x].insta_followers=finfo[0]
                    creds[x].insta_followings=finfo[2]
                else:
                    creds[x].insta_followers=False
                    creds[x].insta_followings=False
            

        return render(request, 'users/mybot.html', {'lcreds':lcreds,'ll':ll, 'packs':packs})

    def post(self, request):
        user = User.objects.get(id=request.user.id) #Get the current user logged in
        ll=LastLogin.objects.get(user=user)
        cred=ll.cred
        fo_info=scrap_us(request.POST.get('insta_user'))
        if request.method == 'POST':
            valid=validat( request.POST.get('insta_user'), request.POST.get('insta_pass') )
            if valid==2:
                user=User.objects.get(id=request.user.id) # Se toma el usuario django que eta logeado.
                cred = Creds()  # inicializacion de Credentials
                cred.user = user  # Se le asigna un usuario a la task
                cred.insta_user=request.POST.get('insta_user')
                cred.insta_pass=request.POST.get('insta_pass')
                cred.imgUrl=scrapImg(request.POST.get('insta_user'))
                cred.pack_id=request.POST.get('pack')
                cred.insta_followers=fo_info[0]
                cred.insta_followings=fo_info[1]
                cred.save()          
                messages.success(request, 'You are welcome %s to Ngage Social' % (request.POST.get('insta_user')))
                return redirect('instabot:userAccounts')
            else:

InstabotMV/templates/users/account.html
{% extends 'dashboard.html' %}

{% block body %}
    <main class="mdl-layout__content">
    <div class="page-content container">
    <br>
<h3>Profile</h3>
    <br>
    <h5><b>First name:</b> {{ user.first_name }}</h5>
    <h5><b>Last name:</b> {{ user.last_name }}</h5>
    <h5><b>Username:</b> {{ user.username }}</h5>
    <h5><b>Email</b> {{ user.email }}</h5>

    <a href="{% url 'instabot:edit_profile' %}" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Editar</a>
    </div>
    </main>
{% endblock %}

InstabotMV/templates/users/accountedit.html
{% extends 'dashboard.html' %}
{% block body %}
    <br>
    <div class="container">
        <div class="card">
        <div class="row">
            <h3 class="center">Edit info account</h3>
            <form class="col s12" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6">
                      <input id="first_name" type="text" class="validate" value="{{ user.first_name }}">
                      <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                      <input id="last_name" type="text" class="validate" value="{{ user.last_name }}">
                      <label for="last_name">Last Name</label>
                    </div>
                </div>
                <div class="row">
                <div class="input-field col s12">
                  <input id="username" type="text" class="validate" value="{{ user.username }}">
                  <label for="username">Username</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <input id="password" type="password" class="validate" value="{{ user.password }}">
                  <label for="password">Password</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <input id="email" type="email" class="validate" value="{{ user.email }}">
                  <label for="email">Email</label>
                </div>
              </div>
                <br>
                <input class="btn" type="submit" value="Actualizar mis datos">
                <br><br>
            </form>
        </div>
    </div>
    </div>

{% endblock %}

InstabotMV/templates/users/addaccount.html
{% extends 'dashboard.html' %}

{% block body %}
<div class="col-md-3"></div>
<div class="container col-md-5 fullscreen2">
        <h5 class="center">Add another account</h5>
        <form action="" method="post">
            {% csrf_token %}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                
                    <input type="text" placeholder="Username"  class="roundedinput2" name="insta_user" maxlength="50" required="" id="insta_user">
            </div>
            <br>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                

                    <input class="roundedinput2" style="" type="password" name="insta_pass" id="insta_pass" placeholder="Password" maxlength="50" required="" id="id_password">
               
                <br><input type="checkbox" onclick="myFunction()">Show Password
            </div>
            <div>
                <br>
                    
                
                    <h5>Please select your package</h5> 
            </div>
            {% csrf_token %}
            <select style="width: 80%;", name="pack" >
                <span class="input-group" >Type in your hashtags or select from a list</span>
  
                {% for  pack in packs %}
                <option value="{{pack.id}}">{{pack.pack_name}}</option>
                {% endfor%}
            </select><!-- -->
            <br>
            <br>
            <script>
                    function myFunction() {
                      var x = document.getElementById("insta_pass");
                      if (x.type === "password") {
                        x.type = "text";        
                      } else {
                        x.type = "password";
                      }
                    }
                    </script>
            <input class="btn btn-success" type="submit"
            
                   value="Add account">
            <br><br>
        </form>
    </div>
    <div class="col-md-4"></div>
    {% endblock %}

InstabotMV/templates/users/blackList.html
{% extends 'dashboard.html' %}

{% block body %}
    <main class="mdl-layout__content">
    <div class="page-content">
    <br>
    <div class="container">
        <div class="card">
        <div class="row">
            <h3 class="center">Hello black list</h3>
            <div class="mdl-textfield mdl-js-textfield getmdl-select">
                <input type="text" value="" class="mdl-textfield__input" id="sample1" readonly>
                <input type="hidden" value="" name="sample1">
                <label for="sample1" class="mdl-textfield__label">Username or Tag</label>
                <ul for="sample1" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    <li class="mdl-menu__item" data-val="DEU">Germany</li>
                    <li class="mdl-menu__item" data-val="BLR">Belarus</li>
                    <li class="mdl-menu__item" data-val="RUS">Russia</li>
                </ul>
            </div>

        </div>
    </div>
    </div>
        </div>
    </main>
{% endblock %}

InstabotMV/templates/users/botDashboard.html
{% extends 'dashboard.html' %}

{% block body %}
    <main class="mdl-layout__content">
    <div class="page-content">
    <br>
    <div class="container">

        <h1>HOlaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</h1>

    </div>
        </div>
    </main>
{% endblock %}

InstabotMV/templates/users/comments.html
{% extends 'dashboard.html' %}

{% load static %}


{% block body %}
    <main class="mdl-layout__content">
    <div class="page-content">
    <br>
    <div class="container">
        <div class="card">
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--4-col">4</div>
            <div class="mdl-cell mdl-cell--4-col">4</div>
            <div class="mdl-cell mdl-cell--4-col">4</div>
            <h3 class="center">hello comments</h3>
            <div class="mdl-textfield mdl-js-textfield getmdl-select">
                <input type="text" value="" class="mdl-textfield__input" id="sample1" readonly>
                <input type="hidden" value="" name="sample1">
                <label for="sample1" class="mdl-textfield__label">First word</label>
                <ul for="sample1" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    <li class="mdl-menu__item" data-val="DEU">Germany</li>
                    <li class="mdl-menu__item" data-val="BLR">Belarus</li>
                    <li class="mdl-menu__item" data-val="RUS">Russia</li>
                </ul>
            </div>
            <div class="mdl-textfield mdl-js-textfield getmdl-select">
                <input type="text" value="" class="mdl-textfield__input" id="sample2" readonly>
                <input type="hidden" value="" name="sample2">
                <label for="sample2" class="mdl-textfield__label">Second word</label>
                <ul for="sample2" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    <li class="mdl-menu__item" data-val="DEU">Germany</li>
                    <li class="mdl-menu__item" data-val="BLR">Belarus</li>
                    <li class="mdl-menu__item" data-val="RUS">Russia</li>
                </ul>
            </div>
            <div class="mdl-textfield mdl-js-textfield getmdl-select">
                <input type="text" value="" class="mdl-textfield__input" id="sample3" readonly>
                <input type="hidden" value="" name="sample3">
                <label for="sample3" class="mdl-textfield__label">Third word</label>
                <ul for="sample3" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    <li class="mdl-menu__item" data-val="DEU">Germany</li>
                    <li class="mdl-menu__item" data-val="BLR">Belarus</li>
                    <li class="mdl-menu__item" data-val="RUS">Russia</li>
                </ul>
            </div>
            <div class="mdl-textfield mdl-js-textfield getmdl-select">
                <input type="text" value="" class="mdl-textfield__input" id="sample4" readonly>
                <input type="hidden" value="" name="sample4">
                <label for="sample4" class="mdl-textfield__label">Fourth word</label>
                <ul for="sample4" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    <li class="mdl-menu__item" data-val="DEU">Germany</li>
                    <li class="mdl-menu__item" data-val="BLR">Belarus</li>
                    <li class="mdl-menu__item" data-val="RUS">Russia</li>
                </ul>
            </div>
            <div class="mdl-textfield mdl-js-textfield getmdl-select">
                <input type="text" value="" class="mdl-textfield__input" id="sample5" readonly>
                <input type="hidden" value="" name="sample5">
                <label for="sample5" class="mdl-textfield__label">Fiveth word</label>
                <ul for="sample15" class=" mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    <li class="mdl-menu__item" data-val="DEU">Germany</li>
                    <li class="mdl-menu__item" data-val="BLR">Belarus</li>
                    <li class="mdl-menu__item" data-val="RUS">Russia</li>
                </ul>
            </div>
        </div>
    </div>
    </div>
        </div>
    </main>

{% endblock %}

InstabotMV/templates/users/del_account.html
{% extends 'base/base.html' %}
{% block navbar %}
<nav class="navbar navbar-inverse">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <a href="{% url 'instabot:dashboard' %}"><h4 class="left navbar-text"></h4></a>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <h4 class="center navbar-text"></h4>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ ll.cred.insta_user }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'instabot:userAccounts' %}">Accounts</a></li>
                            <li><a href="#">Billing Profile</a></li>
                            <li><a href="#">Support</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'instabot:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

{% block body %}
<hr class="divider">
<form method="POST" action="">
    {% csrf_token %}

 <h2>Are you sure to delete this account?</h2>
 <h3>{{cred.insta_user}}</h3>
 <a href="{% url 'instabot:userAccounts'%}" style="float:left;"   class="btn btn-primary" >Back</a>
  <input class="btn btn-danger" style="float:right "href="{% url 'instabot:dashboard'%}" type="submit" value="Yes, Delete!">

</form>

{% endblock %}

InstabotMV/templates/users/mybot.html
{% extends 'dashboard.html' %}

{% block body %}

    <div class="row">
            <h4 class="center">Accounts</h4>
        
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <a href="{% url 'instabot:dashboard' %}" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                Back
            </a>
            <a href="{% url 'instabot:addaccount' %}" class="btn btn-primary pull-left">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    New Account
                </a>
        </div>
    </div>
    <br>
    {% if messages %}
        <div class="row">
            <div class="col-sm-12">
                {% for message in messages %}
                    <h2{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h2>
                {% endfor %}
            </div>
        </div>
    {% endif %}    
    <hr class="divider">

    <div class="row">
        
        {% load static %}
        
        
            <div class="row">
                    {% for cred in lcreds %}
                   
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3" style="margin-right:-100px;margin-left: px;">
                    <div class="thumbnail">
                        <img style="border-radius: 50%; width: 75px;
                        height: 75px;" src="{{cred.imgUrl}}" alt="user-pic">
                        <div class="caption">
                            <h4 class="text-center">{{cred.insta_user}}</h4>
                            {% if cred.insta_followers and cred.ceiling %}
                            <p>Followers: {{cred.insta_followers}}</p>
                            <p>Followings: {{cred.insta_followings}}</p>
                            {%else %}
                            <p>Please check yours credentials or Update your credentials</p>
                            {%endif %}
                            <p>
                                    {% if ll.cred.insta_user == cred.insta_user%}
                                <a href="{% url 'instabot:changeAccount' cred.id %}" style="margin-bottom: 3px;" class="btn btn-primary center-block"  
                                role="button">Current</a>
                                {%else%}
                                
                                <a href="{% url 'instabot:changeAccount' cred.id %}" style="margin-bottom: 3px;" class="btn btn-success center-block"  
                                role="button">Switch</a>
                                {%endif%}
                                <a href="{% url 'instabot:edit_acc' cred.id %}" style="margin-bottom: 3px;" class="btn btn-info center-block"  
                                role="button">Edit</a>
                                <a href="{% url 'instabot:delaccount' cred.id %}" class="btn btn-danger center-block"  
                                role="button">Delete</a>
                            </p>
                        </div>
                    </div>
                </div>
                
                {% endfor %}
            </div>
        
        

    </div>
{% endblock %}

InstabotMV/templates/users/stopBot.html
<form action="" method="post">
    {% csrf_token %}
    <input type="submit"
           class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button-accent"
           value="Stop Bot">
</form>