InstabotMV/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from InstabotMV.views import MediaList


app_name = 'instabot'

urlpatterns = [
    url('show/(?P<username_url>\w+)/$', views.ShowView.as_view(), name='show'),
    url('login/$', views.LoginView.as_view(), name='login'),
    url('logout/$', views.logout, name='logout'),
    url('dashboard/$', views.DashboardView, name='dashboard'),
    url('newaccount/$', views.NewAccount, name='addaccount'),
    url('statics/$', views.loginReport, name='login2'),
    url('dashboard/$', views.tag_child, name='dashload'),
    url('settings/$', views.Settings, name='settings'),
    url('reports/$',views.report, name='report'),
    #url('ajax/ticker/$', views.ticker, name='counter'),
    url('ajax/validate_username/$', views.test, name='test2'),
    url('hashtag_ajax/$', views.hashtags.as_view(), name='hashtags'),
    url('prueba_ajax/$', views.prueba.as_view(), name='prueba'),
    url('dashboard/task/new$', views.NewTask, name='newTask'),
    url('tags/(?P<id_tag>\d+)/$', views.tags, name='tags'),
    url('change/(?P<cred>\d+)/$', views.changeAccount, name='changeAccount'),
    url('dashboard/task/new/follow-like/$', views.NewFollowLike, name='newFollowLike'),
    url('dashboard/task/new/unfollow-task/$', views.UnfollowTask, name='unfollow_task'),
    url('dashboard/accounts/$', views.UserAccounts.as_view(), name='userAccounts'),
    url('dashboard/delaccount/(?P<id_cred>\d+)/$$', views.DeleteAccount, name='delaccount'),
    url('create/$', views.Create, name='create'),
    url('store-new-task/$', views.StoreTask.as_view(), name='storeTask'),
    url('store-new-task-u/$', views.StoreTaskUser.as_view(), name='storeTaskU'),
    url('delete_task/(?P<id_task>\d+)/$', views.DeleteTask,name="del_task"),
    url('edit_acc/(?P<id_acc>\d+)/$', views.EditAccount,name="edit_acc"),
    url('edit_task/(?P<id_task>\d+)/$', views.EditTask,name="edit_task"),
    url('edit_friendtask/(?P<id_task>\d+)/$', views.EditTask2,name="edit_task2"),
    url('edit_unfollowtask/(?P<id_task>\d+)/$', views.EditUnfollow,name="edit_unfollow"),

    # # ******************************** bot url's ************************************************************
    url('start-bot/$', views.StartBot.as_view(),name='start'),
    url('start/(?P<task>\d+)/$', views.start,name='starter'),
    url('stop-bot/(?P<t>\d+)/$', views.detener, name='detener'),
    url('imprimir/$', views.pruebaimpresion, name='impresion'),
    url('generate/$', views.GenerateRandomUserView.as_view(), name='generate')


]

webinstabot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instabotmv/', include('InstabotMV.urls')),
]

InstabotMV/forms.py
from django import forms
from django.contrib.auth.models import User


from InstabotMV.models import Creds, List_Tag, UsList, HashtagList, Media
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())


class CreateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid name'
    })
    last_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid last name'
    })
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'email')


class ProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email field is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })


class InstaCredsForm(forms.ModelForm):
    insta_user = forms.CharField(max_length=30, error_messages={
        'required': 'The username field is required',
        'unique': 'The username entered is already in our records',
        'invalid': 'Enter a valid username'
    })
    insta_pass = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })

    class Meta:
        model = Creds
        fields = ('insta_user', 'insta_pass',)


class TaglistForm(forms.ModelForm):
    insta_tag = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = List_Tag
        fields = ('insta_tag',)


class UserlistForm(forms.ModelForm):
    insta_us_name = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = UsList
        fields = ('insta_us_name',)


class CommandForm(forms.Form):
    command = forms.CharField(max_length=200)


class CombosTagPadre(forms.Form):
    tag_padre = forms.ModelChoiceField(queryset=Media.objects.all())


class ComboTagHijo(forms.Form):
    tag = forms.CharField(label = 'Puntos a sumar', max_length=100, initial='follow, me', required=True)

InstabotMV/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.contrib import messages

from django.contrib.auth import authenticate, login as login_django, logout as logout_django
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import *
from django.urls import reverse
from InstabotMV.models import Creds, List_Tag, Media,HashtagList,Packages
from .forms import LoginForm, CreateUserForm, TaglistForm, UserlistForm, ComboTagHijo
from InstabotMV.forms import InstaCredsForm
from django.db.models import Q

from django.views.generic import View, DetailView, TemplateView, UpdateView, DeleteView, ListView
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http import JsonResponse
import urllib, json
from datetime import date, timedelta
from InstabotMV.src.sql_updates import update_creds
from switchcase import switch
from InstabotMV.src.sql_updates import good_pass
# *************************************************Bot imports**********************************************************

import time

from InstabotMV.src.instabot import InstaBot
from InstabotMV.src.check_status import check_status
from InstabotMV.src.feed_scanner import feed_scanner
from InstabotMV.src.follow_protocol import follow_protocol
from InstabotMV.src.unfollow_protocol import unfollow_protocol
from InstabotMV.src.bsScarp import scrapImg, scrap_us
from InstabotMV.forms import ComboTagHijo
from InstabotMV.src.us_scrap import scrapUsr
from InstabotMV.src.friendListscrap import validat
from InstabotMV.src.sql_updates import update_creds

import smtplib
import datetime
import logging
import random
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic.edit import FormView
from django.shortcuts import redirect


from .forms import GenerateRandomUserForm
from InstabotMV.task import create_random_user_accounts,imprimir,runbot,stop

class GenerateRandomUserView(FormView):
    template_name = 'generate_random_users.html'
    form_class = GenerateRandomUserForm

    def form_valid(self, form):
        total = form.cleaned_data.get('total')
        create_random_user_accounts.delay(total)
        messages.success(self.request, 'We are generating your random users! Wait a moment and refresh this page.')
        return redirect('users_list')

def pruebaimpresion(self):
    imprimir.delay()
    return redirect('instabot:dashboard')
aux=1

def compar_task(task_id, user_n):
    valu=False
    task=Task.objects.all()
    for t in range(0,len(task)):
        if user_n.task==task[t]:
            valu=True
    return valu



# ****************************************************General***********************************************************

def hastagform(request):
    form =ComboTagHijo()
    return render(request, 'includes/audience/hashtags.html',{'form':form})

def hashtag_read(request):
    if request.method =="POST":
            form= ComboTagHijo(request.POST)
            response = ''
            for key, value in request.POST.items():
                response +='key:%s value:%s\n' %(key, value)
                return HttpResponse(response)
    else:
            form= ComboTagHijo(request) #hacemos el formulario en blanco

    return render(request,'includes/audience/hashtags.html',{'form':form})


def tag_child(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        task =Task()#inicializacion de task
        task.user=user#Se le asigna un usuario a la task
        task.save()

        return redirect('instabot:dashload')

    else:
       return redirect('create.html')

def CreateTask(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        task = Task()  # inicializacion de task
        task.user = user  # Se le asigna un usuario a la task
        task.save()

        return redirect('instabot:dashload')

class ShowView(DetailView):
    model = User
    template_name = 'show.html'
    slug_field = 'username'
    slug_url_kwarg = 'username_url'


class LoginView(View):
    form = LoginForm()
    message = " "
    template = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('instabot:dashboard')
        return render(request, self.template, self.get_context())

    def post(self, request, *args, **kwargs):
        username_post = request.POST['username']
        password_post = request.POST['password']
        user = authenticate(username=username_post, password=password_post)
        print(user)
        if user.is_superuser == 1:
            login_django(request, user)
            return redirect('instabot:userAccounts')
        elif user.is_superuser == 0:
            login_django(request, user)
            return redirect('instabot:userAccounts')
        else:
            self.message = "Username o password incorrectos"

        return render(request, self.template, self.get_context())

    def get_context(self):
        return {'form': self.form, 'message': self.message}


@login_required(login_url='instabot:login')
def logout(request):
    logout_django(request)
    return redirect('instabot:login')
@login_required(login_url='/instabotmv/login')
def DashboardView(request):
    user = User.objects.get(id=request.user.id) #Get the current user logged in
    ll=LastLogin.objects.get(user=user)
    cred=ll.cred
    ticklimit=0
    AT=Task.objects.all() #Get All the Task in system
    LT=[] ##Empty list for List of Task
    UX=[]
    z="Hola esto es una prueba"
    count=0
    UN=Username.objects.all() #Limit the ticker number.
    for t in range(0,len(UN)):
        if UN[t].cred_us==ll.cred.insta_user and count<=75 :
            count+=1
            UX.append(UN[t])
    print(ll.cred.insta_user)
    print(len(UX))
    for x in range(0,len(AT)):
       if AT[x].creds==cred:#If the task has the current logged user add it to the LT list
           #print(AT[x].user.username)
           LT.append(AT[x])
           #print("lt se acaba de llenar")
    if len(LT)==0:
        empty=True
        print(LT)
        print("lt esta vacio")
        return render(request, 'dashboard.html', {'ll':ll,'LT':LT,'empty':empty,'UN':UN}) 

    return render(request, 'dashboard.html', {'ll':ll,'LT':LT,'UN':UN,'UX':UX})

def changeAccount(request,cred):
    user = User.objects.get(id=request.user.id)
    ll=LastLogin.objects.get(id=user.id)
    credex= Creds.objects.get(id=cred)
    ll.cred=credex
    ll.save()
    return redirect('instabot:dashboard')




class DashTaskLoad(LoginRequiredMixin, View):  #vista que servira para redireccionar la task guardada en new task excepto paara los unfollows

    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):

        context = {
            'user': request.user
            }

        return render(request, 'dashboard.html', context)


class DashboardClient(LoginRequiredMixin, View):
    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):

        return render(request, 'users/botDashboardClient.html')


class UsersView(LoginRequiredMixin, View):
    login_url = 'instabot:login'

    def get(self, request, *args, **kwargs):
        users_in_system = User.objects.filter(is_superuser=0)

        context = {
            'users': users_in_system
        }
        return render(request, 'admin/clients.html', context)


class UserAccounts(LoginRequiredMixin, View):
    login_url = 'instabot:login'
    template_name = 'users/mybot.html'
    
    
    def get(self, request, *args, **kwargs):
        
        user = User.objects.get(id=request.user.id) #Get the current user logged in
        ll=LastLogin.objects.get(user=user)
        cred=ll.cred
        packs= Packages.objects.all()
        user=User.objects.get(id=request.user.id) #Obtencion del usuario logeado
        creds = Creds.objects.all() #Obtencion de todas las credenciales 
        lcreds=[] #Inicializacion de lista de credenciales
        finfo=[]

        for x in range(0,len(creds)):
            #print(creds[x].ceiling)
            if creds[x].user==user:
                lcreds.append(creds[x])
                finfo=scrap_us(creds[x].insta_user)
                if finfo:
                    creds[x].insta_followers=finfo[0]
                    creds[x].insta_followings=finfo[2]
                else:
                    creds[x].insta_followers=False
                    creds[x].insta_followings=False
            

        return render(request, 'users/mybot.html', {'lcreds':lcreds,'ll':ll, 'packs':packs})

    def post(self, request):
        user = User.objects.get(id=request.user.id) #Get the current user logged in
        ll=LastLogin.objects.get(user=user)
        cred=ll.cred
        fo_info=scrap_us(request.POST.get('insta_user'))
        if request.method == 'POST':
            valid=validat( request.POST.get('insta_user'), request.POST.get('insta_pass') )
            if valid==2:
                user=User.objects.get(id=request.user.id) # Se toma el usuario django que eta logeado.
                cred = Creds()  # inicializacion de Credentials
                cred.user = user  # Se le asigna un usuario a la task
                cred.insta_user=request.POST.get('insta_user')
                cred.insta_pass=request.POST.get('insta_pass')
                cred.imgUrl=scrapImg(request.POST.get('insta_user'))
                cred.pack_id=request.POST.get('pack')
                cred.insta_followers=fo_info[0]
                cred.insta_followings=fo_info[1]
                cred.save()          
                messages.success(request, 'You are welcome %s to Ngage Social' % (request.POST.get('insta_user')))
                return redirect('instabot:userAccounts')
            else:

InstabotMV/templates/tasks/del_task.html
{% extends 'base/base.html' %}
{% block navbar %}
<nav class="navbar navbar-inverse">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <a href="{% url 'instabot:dashboard' %}"><h4 class="left navbar-text">Ngage Social</h4></a>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <h4 class="center navbar-text">CURRENT PLAN</h4>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ ll.cred.insta_user }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'instabot:userAccounts' %}">Accounts</a></li>
                            <li><a href="#">Billing Profile</a></li>
                            <li><a href="#">Support</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'instabot:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

{% block body %}

<form method="POST" action="">
    {% csrf_token %}

 <p>Esta seguro que desea eliminar la task?</p>
  <input href="{% url 'instabot:dashboard'%}" type="submit" value="Eliminar">

</form>

{% endblock %}

InstabotMV/templates/tasks/newTask.html
{% extends 'dashboard.html' %}
{% block body %}
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h4 class="left">Task Type</h4>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <a href="{% url 'instabot:dashboard' %}" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                Back
            </a>
        </div>
    </div>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <hr class="divider">
    <h4 class="text-center"><b>Please choose your task type</b></h4>
    <br>
    <div class="row">
        <div class="col-md-6">
            <p>Select Like, Follow task, if you want to automatically Like/Follow targeted people by given criteria.</p>
            <a href="{% url 'instabot:newFollowLike' %}" class="btn btn-primary">
                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                CREATE NEW AUTOMATED LIKE, FOLLOW TASK
            </a>
        </div>
        <div class="col-md-6">
            <p>Select Unfollow task, if you want to automatically Unfollow your Following by given criteria.</p>
            <a href="{% url 'instabot:unfollow_task'%}" class="btn btn-primary"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
                CREATE NEW AUTOMATED UNFOLLOW TASK
            </a>
        </div>
    </div>
{% endblock %}

InstabotMV/templates/tasks/unfollow_task.html
{% extends 'dashboard.html' %}
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Ngage Social</title>

    <!-- Another Css -->


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/bootstrap-tokenfield.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


<script src="{% static 'js/bootstrap-tokenfield.js' %}"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/styles.js' %}"></script>
<script src="{% static 'js/hashtags.js' %}"></script>
<script src="{% static 'js/usernames.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/classhashtag.js'%}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery-1.12.4.min.js">\x3C/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="container">
{% block body %}
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h4 class="left">New Task</h4>
        </div>
        
    </div>

    <hr class="divider">

    <div id="exTab2" class="container">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
        <link href="https://fonts.googleapis.com/css?family=Hind" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js"></script>
        <div class="tab-content ">
            
            <form method="POST" id="formulario" >
                    {% csrf_token %}
                <link rel="stylesheet" href="{% static 'css/tags.css' %}">
                <p>Select users which you want to unfollow</p>
                <div class="row" style="text-align:center;">

                    <label class="radio-inline">
                        <input  style="transform: scale(1.5);" type="radio" name="optradio" id="ngage" checked value="True">Users followed by Ngage Social 
                      </label>
                      <label  class="radio-inline">
                        <input style="transform: scale(1.5);"type="radio" name="optradio" id="all" value="false" >All users 
                </div>
                        <br>
                            <script src="{% static 'js/tags.js' %}"></script>
                
                <p>You can target your unfollowing more accurately with additional features</p>
                <div class="row">
                    <div class="col-md-12">
                        <a onclick="toggle_visibility('check21');" style="overflow:auto; border-radius: 5px;border:none;" style="overflow:auto;" id="btnghost"class="btn btn-primary btn-block">
                            <span style="float:left; margin-right: 5px;"class="far fa-flushed"></span>
                            <p style="float:left;">UNFOLLOW ONLY IF USER IS GHOST, NON ACTIVE</p>
                            <input name="ghost" id="ghost" value="ghost" type="hidden">
                            <div style="float:right;
                                    width:100px;"class="col-md-2">
                                        <span id="check21" class="check21 fa fa-check fa-2x"   aria-hidden="true"></span>
                                      </div>
                            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet" />
<script>
    function toggle_visibility(id) {
var e = document.getElementById(id);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
}

     </script>
<script>
    $(document).ready(function() {
var toggleText = $("#ip").val();
$("#btnghost").click(function() {
if ($("#ghost").val() != 'none') {
toggleText = $("#ghost").val();
$("#ghost").val('none');
} else
$("#ghost").val(toggleText);
$(this).toggleClass('grey');

});
});
    </script>
                           
                        </a>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <a onclick="toggle_visibility('check22');" style="overflow:auto; border-radius: 5px;border:none;" id="btnback"style="overflow:auto;" class="btn btn-primary btn-block">
                            <span style="float:left; margin-right: 5px;"class="far fa-frown"></span>
                            <input name="back" id="back" value="back" type="hidden">
                            <div style="float:right;
                            width:100px;"class="col-md-2">
                                <span id="check22" class="check22 fa fa-check fa-2x"   aria-hidden="true"></span>
                              </div>
                            <script>
                                function toggle_visibility(id) {
                            var e = document.getElementById(id);
                            e.style.display = ((e.style.display!='none') ? 'none' : 'block');
                            }
                            
                                 </script>
                            <script>
                                $(document).ready(function() {
                            var toggleText = $("#ip").val();
                            $("#btnback").click(function() {
                            if ($("#back").val() != 'none') {
                            toggleText = $("#back").val();
                            $("#back").val('none');
                            } else
                            $("#back").val(toggleText);
                            $(this).toggleClass('grey');
                            
                            });
                            });
                                </script>
                            <p style="float:left;">UNFOLLOW ONLY IF USER HAVEN'T FOLLOWED YOU BACK</p>
                            
                        </a>
                    </div>
                </div>
                
                <br>
               
                
                
                
                
                
                
                <input style="opacity:0; position:absolute; left:9999px;"type="checkbox" id="randomly" name="randomly" aria-label="...">  <br>
                
                
                
                
                <input style="opacity:0; position:absolute; left:9999px;" type="checkbox" id="antispam" name="antispam" aria-label="...">  <br>
                
                <input style="opacity:0; position:absolute; left:9999px;" type="checkbox" id="custom" name="custom" aria-label="...">  <br>
                <br>
                <div class="row">
                        <div class="x">
                <button style="float: right;"type="submit" class="btn btn-primary">save</button>
            </div>
            <div class="y">
                    <a href="{% url 'instabot:newTask' %}" class="btn btn-primary ">  <!--Se invoca la view para volver -->
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        Back
                    </a>
                </div></div>
            
            </form>




   <!-- <div class="row">
        <div class="col-md-12">
            <div>
                <button type="checkbox" id="x" href="#" class="btn btn-primary" onclick="myFunction()">
                    <span class="glyphicon glyphicon-heart" aria-hidden="false"></span>
                    LIKE MEDIA OF THIS TASK
                </button>
                </div>
            <script>
function myFunction() {
  document.getElementById("x").disabled = true;
}
</script>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <button href="#" class="btn btn-primary" disabled="true">
                <span class="glyphicon glyphicon-user"></span>
                FOLLOW USER OF THIS TASK MEDIA
            </button>
    <p>Select features</p>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-12">
            <button href="#" class="btn btn-primary">
                <span class=" icn-chang glyphicon glyphicon-eye-open "></span>
                DON'T LIKE MEDIA OF THE SAME USER SECOND TIME
            </button>
        </div>

    </div>
    <br>
    <div class="row">
        <div class="col-md-12">

            <button href="#" class="btn btn-primary">
                <span class="glyphicon glyphicon-sunglasses"></span>
                DON'T FOLLOW PREVIOUSLY UNFOLLOWED USER
            </button>
        </div>

    </div>

    <br>
    <div class="row">
        <div class="col-md-12">
            <button href="#" class="btn btn-primary">
                <span class="glyphicon glyphicon-dashboard"></span>
                SEARCH FOR RECENTLY POSTED MEDIA ONLY
            </button>

        </div>
    </div>

    <br>

    -->

            </div>


        </div>
    </div>
</div>
{% endblock %}