InstabotMV/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from InstabotMV.views import MediaList


app_name = 'instabot'

urlpatterns = [
    url('show/(?P<username_url>\w+)/$', views.ShowView.as_view(), name='show'),
    url('login/$', views.LoginView.as_view(), name='login'),
    url('logout/$', views.logout, name='logout'),
    url('dashboard/$', views.DashboardView, name='dashboard'),
    url('newaccount/$', views.NewAccount, name='addaccount'),
    url('statics/$', views.loginReport, name='login2'),
    url('dashboard/$', views.tag_child, name='dashload'),
    url('settings/$', views.Settings, name='settings'),
    url('reports/$',views.report, name='report'),
    #url('ajax/ticker/$', views.ticker, name='counter'),
    url('ajax/validate_username/$', views.test, name='test2'),
    url('hashtag_ajax/$', views.hashtags.as_view(), name='hashtags'),
    url('prueba_ajax/$', views.prueba.as_view(), name='prueba'),
    url('dashboard/task/new$', views.NewTask, name='newTask'),
    url('tags/(?P<id_tag>\d+)/$', views.tags, name='tags'),
    url('change/(?P<cred>\d+)/$', views.changeAccount, name='changeAccount'),
    url('dashboard/task/new/follow-like/$', views.NewFollowLike, name='newFollowLike'),
    url('dashboard/task/new/unfollow-task/$', views.UnfollowTask, name='unfollow_task'),
    url('dashboard/accounts/$', views.UserAccounts.as_view(), name='userAccounts'),
    url('dashboard/delaccount/(?P<id_cred>\d+)/$$', views.DeleteAccount, name='delaccount'),
    url('create/$', views.Create, name='create'),
    url('store-new-task/$', views.StoreTask.as_view(), name='storeTask'),
    url('store-new-task-u/$', views.StoreTaskUser.as_view(), name='storeTaskU'),
    url('delete_task/(?P<id_task>\d+)/$', views.DeleteTask,name="del_task"),
    url('edit_acc/(?P<id_acc>\d+)/$', views.EditAccount,name="edit_acc"),
    url('edit_task/(?P<id_task>\d+)/$', views.EditTask,name="edit_task"),
    url('edit_friendtask/(?P<id_task>\d+)/$', views.EditTask2,name="edit_task2"),
    url('edit_unfollowtask/(?P<id_task>\d+)/$', views.EditUnfollow,name="edit_unfollow"),

    # # ******************************** bot url's ************************************************************
    url('start-bot/$', views.StartBot.as_view(),name='start'),
    url('start/(?P<task>\d+)/$', views.start,name='starter'),
    url('stop-bot/(?P<t>\d+)/$', views.detener, name='detener'),
    url('imprimir/$', views.pruebaimpresion, name='impresion'),
    url('generate/$', views.GenerateRandomUserView.as_view(), name='generate')


]

webinstabot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instabotmv/', include('InstabotMV.urls')),
]

InstabotMV/models.py
from django.db import models
from django.contrib.auth.models import User


# class UserInsta(models.Model):
# username_insta = models.CharField(max_length=30)
# password_insta = models.CharField(max_length=30)
class AppUser(User):
   insta_user = models.CharField(max_length=150)
   insta_pass = models.CharField(max_length=50)

   class Meta:
       verbose_name = 'AppUser'
       verbose_name_plural = 'AppUsers'

   def __str__(self):
       return '%s' % (self.username)


class Packages(models.Model):  #PAQUETES DE USUARIO
    pack_name= models.CharField(max_length=30)
    follows_by_pack=models.IntegerField()
    like_by_pack=models.IntegerField()
    

class Settings(models.Model):
    settings_name = models.TextField()
    settings_val = models.TextField()


class Creds(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    insta_user = models.CharField(max_length=150)
    insta_pass = models.CharField(max_length=50)
    imgUrl=models.TextField()
    pack=models.ForeignKey(Packages, on_delete=models.CASCADE) #TIPO DE PAQUETE QUE HA ELEGIDO EL USUARIO
    ceiling=models.BooleanField(default=True)
    number_ceiling= models.IntegerField(null=True)
    insta_followers=models.CharField(max_length=20)
    insta_followings=models.CharField(max_length=20)
    
    class Meta:
        verbose_name = 'Cred'
        verbose_name_plural = 'Creds'

    def __str__(self):
        return '%s' % (self.insta_user)

class Task(models.Model):
    creds=models.ForeignKey(Creds,on_delete=models.CASCADE)
    active=models.BooleanField()
    tags=models.CharField(max_length=1000)
    likemedia=models.BooleanField()
    followuser=models.BooleanField()
    dontlikemedia=models.BooleanField()
    dontfollow=models.BooleanField()
    sleep_mod=models.BooleanField(default=False)
    search=models.BooleanField()
    unfollow=models.BooleanField()
    ghost=models.BooleanField()
    back=models.BooleanField()
    follwers_user=models.BooleanField(default=False)
    followeds_user=models.BooleanField(default=False)
    allusers=models.BooleanField(default=False)
    friendlist=models.BooleanField()#esta sera el campo para ver si el friendlist esta activo

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return '%s' % (self.tags)


class Media(models.Model):
    task=models.IntegerField()
    media_id = models.CharField(max_length=300)
    status = models.IntegerField()
    datetime = models.DateTimeField()
    code = models.TextField()
    owner_name = models.CharField(max_length=100)
    cred_us = models.CharField(max_length=100)
    picUrl=models.TextField()
    


class Username(models.Model):
    task=models.IntegerField()
    username = models.CharField(max_length=300)
    username_id = models.CharField(max_length=300)
    unfollow_count = models.IntegerField()
    last_followed_time = models.DateTimeField(null=True)
    unfollowed_time=models.DateTimeField(null=True)
    cred_us = models.CharField(max_length=100)
    picUrl=models.TextField()
    
class Comments(models.Model):
    insta_comment = models.CharField(max_length=200)
    timestamp = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class BlackList(models.Model):
    insta_black_list = models.CharField(max_length=200)
    timestamp = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class HashtagList(models.Model):
    category = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'HashtagList'
        verbose_name_plural = 'HashtagLists'

    def __str__(self):
        return '%s' % (self.category)


class UsList(models.Model):
    insta_us_name = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class LocateList(models.Model):
    insta_locate = models.TextField()
    timestamp = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class List_Tag(models.Model):
    insta_tag = models.CharField(max_length=100)
    category = models.ForeignKey(HashtagList, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'List_Tag'
        verbose_name_plural = 'List_Tags'

    def __str__(self):
        return '%s' % (self.insta_tag)



class Features(models.Model):
    id_feature= models.IntegerField(primary_key=True)
    feature_name = models.CharField(max_length=100)


class ChildTag(models.Model):
    tag_name= models.CharField(max_length=100)
    hashtag_id = models.IntegerField(primary_key=True,)
    dad_tag = models.ForeignKey(HashtagList, on_delete=models.CASCADE)
#Lectura de hasgtags para el task



class LastLogin(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    cred=models.ForeignKey(Creds,on_delete=models.SET_NULL, null=True)
    class Meta:
        verbose_name = 'lastLogin'
        verbose_name_plural = 'lastLogin'

    def __str__(self):
        return '%s' % (self.user)

class thread(models.Model):
    task=models.ForeignKey(Task, on_delete=models.CASCADE)
    codigo=models.CharField(max_length=1000)
    class Meta:
        verbose_name = 'thread'
        verbose_name_plural = 'threads'

    def __str__(self):
        return '%s' % (self.task.tags)


class bitacora(models.Model):
    Cred=models.ForeignKey(Creds,on_delete=models.CASCADE)
    followers=models.IntegerField()
    followings=models.IntegerField()
    datetime=models.DateTimeField()
    #followincrease=models.IntegerField()
    #followingincrease=models.IntegerField()       

class post(models.Model):
    Cred=models.ForeignKey(Creds,on_delete=models.CASCADE)
    number=models.IntegerField()
    urlpic=models.CharField(max_length=1000)
    date=models.CharField(max_length=1000)
    comments=models.CharField(max_length=1000)
    like=models.CharField(max_length=1000)

InstabotMV/forms.py
from django import forms
from django.contrib.auth.models import User


from InstabotMV.models import Creds, List_Tag, UsList, HashtagList, Media
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())


class CreateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid name'
    })
    last_name = forms.CharField(max_length=20, error_messages={
        'required': 'The field is required',
        'invalid': 'Enter a valid last name'
    })
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'email')


class ProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=20, error_messages={
        'required': 'The username field is required',
        'unique': 'The username is already taken',
        'invalid': 'Enter a valid username'
    })
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })
    email = forms.CharField(error_messages={
        'required': 'The email field is required',
        'unique': 'The email is already associated with an account',
        'invalid': 'Enter a valid email'
    })


class InstaCredsForm(forms.ModelForm):
    insta_user = forms.CharField(max_length=30, error_messages={
        'required': 'The username field is required',
        'unique': 'The username entered is already in our records',
        'invalid': 'Enter a valid username'
    })
    insta_pass = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages={
        'required': 'The password field is required'
    })

    class Meta:
        model = Creds
        fields = ('insta_user', 'insta_pass',)


class TaglistForm(forms.ModelForm):
    insta_tag = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = List_Tag
        fields = ('insta_tag',)


class UserlistForm(forms.ModelForm):
    insta_us_name = forms.CharField(error_messages={
        'required': 'Please insert some data',
    })

    class Meta:
        model = UsList
        fields = ('insta_us_name',)


class CommandForm(forms.Form):
    command = forms.CharField(max_length=200)


class CombosTagPadre(forms.Form):
    tag_padre = forms.ModelChoiceField(queryset=Media.objects.all())


class ComboTagHijo(forms.Form):
    tag = forms.CharField(label = 'Puntos a sumar', max_length=100, initial='follow, me', required=True)

InstabotMV/templates/includes/dialog.html
<dialog id="dialog" class="mdl-dialog">
  <h3 class="mdl-dialog__title center">Register new client account</h3>
  <div class="mdl-dialog__content">
      <form action="{% url 'instabot:create' %}" role="form" class="col s12" method="post">
          {% csrf_token %}

          <h4 class="center">Sistem Creds</h4>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-textfield__label" for="id_first_name">First name:</label>
              <input class="mdl-textfield__input" type="text" name="first_name" maxlength="30" required=""
                     id="id_first_name">
          </div>
          <br>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-textfield__label" for="id_last_name">Last name:</label>
              <input class="mdl-textfield__input" type="text" name="last_name" maxlength="30" required=""
                     id="id_last_name">
          </div>
          <br>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-textfield__label" for="id_username">Username:</label>
              <input class="mdl-textfield__input" type="text" name="username" maxlength="30" required=""
                     id="id_username">
          </div>
          <br>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-textfield__label" for="id_email">Email:</label>
              <input class="mdl-textfield__input" type="email" name="email" maxlength="30" required=""
                     id="id_email">
          </div>
          <br>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">

              <input class="mdl-textfield__input" type="hidden" name="password" maxlength="30" required=""
                     id="id_password" value="myinstagrambot">
          </div>
          <br>
          <h4 class="center">Instagram Creds</h4>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-textfield__label" for="id_insta_user">Insta user:</label>
              <input class="mdl-textfield__input" type="text" name="insta_user" maxlength="30" required=""
                     id="id_insta_user">
          </div>
          <br>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-textfield__label" for="id_insta_pass">Insta pass:</label>
              <input class="mdl-textfield__input" type="password" name="insta_pass" maxlength="30" required=""
                     id="id_insta_pass">
          </div>
          <br>
          <input class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit"
                 value="Register">
          <br><br>
      </form>
  </div>
  <div class="mdl-dialog__actions">
    <button type="button" class="mdl-button">Close</button>
    <button type="button" class="mdl-button">Save</button>
  </div>
</dialog>

InstabotMV/templates/includes/settings.html
<dialog id="settings" class="mdl-dialog">
  <h3 class="mdl-dialog__title center">User Settings</h3>
  <div class="mdl-dialog__content">
      <div>
          <h5 class="center">Blacklist</h5>
          <div class="mdl-textfield mdl-js-textfield getmdl-select">
              <input type="text" value="" class="mdl-textfield__input" id="sample9" readonly>
              <input type="hidden" value="" name="sample9">
              <label for="sample9" class="mdl-textfield__label">Username or Tag</label>
              <ul for="sample9" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                  <li class="mdl-menu__item" data-val="DEU">Drugs</li>
                  <li class="mdl-menu__item" data-val="BLR">Canabis</li>
                  <li class="mdl-menu__item" data-val="RUS">AMLO</li>
              </ul>
          </div>
      </div>
      <div>
          <h5 class="center">Whitelist</h5>
          <div class="mdl-textfield mdl-js-textfield getmdl-select">
              <input type="text" value="" class="mdl-textfield__input" id="sample8" readonly>
              <input type="hidden" value="" name="sample8">
              <label for="sample8" class="mdl-textfield__label">Username or Tag</label>
              <ul for="sample8" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                  <li class="mdl-menu__item" data-val="DEU">Food</li>
                  <li class="mdl-menu__item" data-val="BLR">Pets</li>
                  <li class="mdl-menu__item" data-val="RUS">Obama</li>
              </ul>
          </div>
      </div>
      <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--6-col center-block">
              <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
                  <i class="material-icons">play_arrow</i>
              </button>
          </div>
          <div class="mdl-cell mdl-cell--6-col">
              <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--accent">
                  <i class="material-icons">stop</i>
              </button>
          </div>
      </div>
  </div>
  <div class="mdl-dialog__actions">
    <button type="button" class="mdl-button">Close</button>
    <button type="button" class="mdl-button">Save</button>
  </div>
</dialog>